package programtotalbite;

import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager.LookAndFeelInfo;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.mysql.jdbc.Statement;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

public class TotalBite extends javax.swing.JFrame {
    private Statement St;
    private Connection Con;
    private ResultSet Rs;
    private String sql = "";
    private Object jtxtl;
    private Object area;
    private String NoOrder, NamaPemesan, PesananMakanan, PesananMinuman, Tanggal;
    private int HargaMakanan, HargaMinuman, SubTotal, Total, Bayar;
    
 public TotalBite() {
    initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jText1 = new javax.swing.JTextField();
        jText2 = new javax.swing.JTextField();
        jText3 = new javax.swing.JTextField();
        jText4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jText5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jText6 = new javax.swing.JTextField();
        jText7 = new javax.swing.JTextField();
        jText8 = new javax.swing.JTextField();
        jText9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jText10 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jText11 = new javax.swing.JTextField();
        jText12 = new javax.swing.JTextField();
        jText13 = new javax.swing.JTextField();
        jText19 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jText14 = new javax.swing.JTextField();
        jText15 = new javax.swing.JTextField();
        jText16 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jText17 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jText18 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButtonData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 63, 63));

        jPanel1.setBackground(new java.awt.Color(43, 63, 63));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 158, 55), 12));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(176, 158, 55));
        jLabel2.setText("Bakso / Rp 12.000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(176, 158, 55));
        jLabel3.setText("Mie Ayam / Rp 10.000");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(176, 158, 55));
        jLabel4.setText("Nasi Goreng / Rp 12.000");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(176, 158, 55));
        jLabel5.setText("Ayam Bakar / Rp 15.000");

        jText1.setBackground(new java.awt.Color(176, 158, 55));
        jText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText1.setForeground(new java.awt.Color(51, 51, 51));
        jText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText1.setText("0");
        jText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText1ActionPerformed(evt);
            }
        });

        jText2.setBackground(new java.awt.Color(176, 158, 55));
        jText2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText2.setForeground(new java.awt.Color(51, 51, 51));
        jText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText2.setText("0");
        jText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText2ActionPerformed(evt);
            }
        });

        jText3.setBackground(new java.awt.Color(176, 158, 55));
        jText3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText3.setForeground(new java.awt.Color(51, 51, 51));
        jText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText3.setText("0");
        jText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText3ActionPerformed(evt);
            }
        });

        jText4.setBackground(new java.awt.Color(176, 158, 55));
        jText4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText4.setForeground(new java.awt.Color(51, 51, 51));
        jText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText4.setText("0");
        jText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(176, 158, 55));
        jLabel14.setText("Soto / Rp 14.000");

        jText5.setBackground(new java.awt.Color(176, 158, 55));
        jText5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText5.setForeground(new java.awt.Color(51, 51, 51));
        jText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText5.setText("0");
        jText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(176, 158, 55));
        jLabel7.setText("'Menu Makanan'");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(43, 63, 63));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));
        jPanel3.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(176, 158, 55));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(176, 158, 55));
        jLabel1.setText("Aplikasi TotalBite");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(43, 63, 63));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(176, 158, 55));
        jLabel10.setText("Es Jeruk / Rp 6.000");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(176, 158, 55));
        jLabel11.setText("Es Teh / Rp 6.000");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(176, 158, 55));
        jLabel12.setText("Teh Hangat / Rp 6.000");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(176, 158, 55));
        jLabel13.setText("Air Mineral / Rp 5.000");

        jText6.setBackground(new java.awt.Color(176, 158, 55));
        jText6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText6.setForeground(new java.awt.Color(51, 51, 51));
        jText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText6.setText("0");
        jText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText6ActionPerformed(evt);
            }
        });

        jText7.setBackground(new java.awt.Color(176, 158, 55));
        jText7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText7.setForeground(new java.awt.Color(51, 51, 51));
        jText7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText7.setText("0");
        jText7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText7ActionPerformed(evt);
            }
        });

        jText8.setBackground(new java.awt.Color(176, 158, 55));
        jText8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText8.setForeground(new java.awt.Color(51, 51, 51));
        jText8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText8.setText("0");
        jText8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText8ActionPerformed(evt);
            }
        });

        jText9.setBackground(new java.awt.Color(176, 158, 55));
        jText9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText9.setForeground(new java.awt.Color(51, 51, 51));
        jText9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText9.setText("0");
        jText9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText9ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(176, 158, 55));
        jLabel15.setText("Nutrisari / Rp 6.000");

        jText10.setBackground(new java.awt.Color(176, 158, 55));
        jText10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText10.setForeground(new java.awt.Color(51, 51, 51));
        jText10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText10.setText("0");
        jText10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText10ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(176, 158, 55));
        jLabel6.setText("'Menu Minuman'");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jText10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel15)))
                .addGap(27, 27, 27))
        );

        jPanel10.setBackground(new java.awt.Color(43, 63, 63));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(176, 158, 55));
        jLabel16.setText("Harga Makanan");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(176, 158, 55));
        jLabel17.setText("Harga Minuman");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(176, 158, 55));
        jLabel18.setText("Total Pesanan");

        jText11.setBackground(new java.awt.Color(176, 158, 55));
        jText11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText11.setForeground(new java.awt.Color(51, 51, 51));
        jText11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText11ActionPerformed(evt);
            }
        });

        jText12.setBackground(new java.awt.Color(176, 158, 55));
        jText12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText12.setForeground(new java.awt.Color(51, 51, 51));
        jText12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText12ActionPerformed(evt);
            }
        });

        jText13.setBackground(new java.awt.Color(176, 158, 55));
        jText13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText13.setForeground(new java.awt.Color(51, 51, 51));
        jText13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText13ActionPerformed(evt);
            }
        });

        jText19.setBackground(new java.awt.Color(176, 158, 55));
        jText19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText19.setForeground(new java.awt.Color(51, 51, 51));
        jText19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText19ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(176, 158, 55));
        jLabel24.setText("Nama Pemesan");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jText11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(43, 63, 63));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(176, 158, 55));
        jLabel19.setText("SubTotal");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(176, 158, 55));
        jLabel20.setText("Pajak");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(176, 158, 55));
        jLabel21.setText("Total");

        jText14.setBackground(new java.awt.Color(176, 158, 55));
        jText14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText14.setForeground(new java.awt.Color(51, 51, 51));
        jText14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText14ActionPerformed(evt);
            }
        });

        jText15.setBackground(new java.awt.Color(176, 158, 55));
        jText15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText15.setForeground(new java.awt.Color(51, 51, 51));
        jText15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText15ActionPerformed(evt);
            }
        });

        jText16.setBackground(new java.awt.Color(176, 158, 55));
        jText16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText16.setForeground(new java.awt.Color(51, 51, 51));
        jText16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText16ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(176, 158, 55));
        jLabel22.setText("Bayar");

        jText17.setBackground(new java.awt.Color(176, 158, 55));
        jText17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText17.setForeground(new java.awt.Color(51, 51, 51));
        jText17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText17ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(176, 158, 55));
        jLabel23.setText("Kembalian");

        jText18.setBackground(new java.awt.Color(176, 158, 55));
        jText18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText18.setForeground(new java.awt.Color(51, 51, 51));
        jText18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jText14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(387, 387, 387))
        );

        jPanel12.setBackground(new java.awt.Color(43, 63, 63));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));

        jButton1.setBackground(new java.awt.Color(176, 158, 55));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(176, 158, 55));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(176, 158, 55));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(51, 51, 51));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(176, 158, 55));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(194, 194, 194)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButtonExit)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(43, 63, 63));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 158, 55), 12, true));

        jTextArea1.setBackground(new java.awt.Color(176, 158, 55));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" ");
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setBackground(new java.awt.Color(176, 158, 55));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonData.setBackground(new java.awt.Color(176, 158, 55));
        jButtonData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonData.setForeground(new java.awt.Color(51, 51, 51));
        jButtonData.setText("Data");
        jButtonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButtonData))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 818, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText1ActionPerformed

    private void jText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText2ActionPerformed

    private void jText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText3ActionPerformed

    private void jText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText4ActionPerformed

    private void jText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText6ActionPerformed

    private void jText7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText7ActionPerformed

    private void jText8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText8ActionPerformed

    private void jText9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText9ActionPerformed

    private void jText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText5ActionPerformed

    private void jText10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText10ActionPerformed

    private void jText11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText11ActionPerformed

    private void jText12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText12ActionPerformed

    private void jText13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText13ActionPerformed

    private void jText14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText14ActionPerformed

    private void jText15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText15ActionPerformed

    private void jText16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText16ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Reset
        jText1.setText("0");
        jText2.setText("0");
        jText3.setText("0");
        jText4.setText("0");
        jText5.setText("0");
        jText6.setText("0");
        jText7.setText("0");
        jText8.setText("0");
        jText9.setText("0");
        jText10.setText("0");
        jText11.setText("");
        jText12.setText("");
        jText13.setText("");
        jText14.setText("");
        jText15.setText("");
        jText16.setText("");
        jText17.setText("");
        jText18.setText("");
        jTextArea1.setText(null); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // Exit
        SubClass iExit = new SubClass();
        iExit.iExitSystem();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Total
    SubClass ItemCost = new SubClass();
    double iPajak, iSubtotal, iTotal;
    
    ItemCost.Bakso = ItemCost.hBakso * Double.parseDouble(jText1.getText());
    ItemCost.MieAyam = ItemCost.hMieAyam * Double.parseDouble(jText2.getText());
    ItemCost.NasiGoreng = ItemCost.hNasiGoreng * Double.parseDouble(jText3.getText());
    ItemCost.AyamBakar = ItemCost.hAyamBakar * Double.parseDouble(jText4.getText());
    ItemCost.Soto = ItemCost.hSoto * Double.parseDouble(jText5.getText());
    
    ItemCost.EsJeruk = ItemCost.hEsJeruk * Double.parseDouble(jText6.getText());
    ItemCost.EsTeh = ItemCost.hEsTeh * Double.parseDouble(jText7.getText());
    ItemCost.TehHangat = ItemCost.hTehHangat * Double.parseDouble(jText8.getText());
    ItemCost.AirMineral = ItemCost.hAirMineral * Double.parseDouble(jText9.getText());
    ItemCost.Nutrisari = ItemCost.hNutrisari * Double.parseDouble(jText10.getText());
    
    iSubtotal = ItemCost.GetAmount();
    iPajak = ItemCost.hitungPajak(iSubtotal);
    iTotal = iSubtotal + iPajak;
    
    String SubTotal = String.format("Rp%.2f"+"0", iSubtotal);
    jText14.setText(SubTotal);
    
    String Pajak = String.format("Rp%.2f"+"0", iPajak);
    jText15.setText(Pajak);
    
    String Total = String.format("Rp%.2f"+"0", iTotal);
    jText16.setText(Total);
    
    String Makanan = String.format("Rp%.2f"+"0", ItemCost.Makanan);
    jText11.setText(Makanan);
    
    String Minuman = String.format("Rp%.2f"+"0", ItemCost.Minuman);
    jText12.setText(Minuman);
    
    String TotalCost = String.format("Rp%.2f"+"0", ItemCost.TotalMM);
    jText13.setText(TotalCost);
    
    // Bayar
    try {
        // Mendapatkan input uang yang dibayarkan dari jText17
        double uangBayar = Double.parseDouble(jText17.getText());
        
        // Menampilkan uang yang dibayarkan di jTextArea1
        String bayar = String.format("Rp%.2f"+"0", uangBayar);
        jText17.setText(bayar);
        // Menghitung dan menampilkan kembalian di jText18
        double kembalian = uangBayar - iTotal;
        String kembali = String.format("Rp%.2f"+"0", kembalian);
        jText18.setText(kembali);
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika pengguna memasukkan input yang tidak valid
        JOptionPane.showMessageDialog(this, "Pastikan jumlah total dan uang bayar adalah angka yang valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // Receipt
    try {
       // Mendapatkan nomor order secara acak
        int nomerOrder = 1001 + (int) (Math.random() * 11);

        // Mendapatkan waktu sekarang
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("yyyy-MM-dd");
        tDate.format(timer.getTime());

        // Mengambil nilai dari input pengguna
        String namaPemesan = jText19.getText();
        String makanan = jText11.getText();
        String minuman = jText12.getText();

        // Membersihkan nilai dari karakter tidak valid
        String totalBayarText = jText16.getText().replace("Rp", "").replace(".", "");
        String uangBayarText = jText17.getText().replace("Rp", "").replace(".", "");

        // Mengonversi nilai yang sudah dibersihkan menjadi bilangan desimal
        double totalBayar = Double.parseDouble(totalBayarText);
        double uangBayar = Double.parseDouble(uangBayarText);

        // Membuat koneksi ke database dan menjalankan query INSERT
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/TotalBite", "root", "");
        Statement St = (Statement) connection.createStatement();

        String sql = "INSERT INTO Receipt (nomerOrder, namaPemesan, makanan, minuman, totalBayar, uangBayar, kembalian, tglTransaksi, waktuTransaksi) VALUES ('"
                + nomerOrder + "','"
                + namaPemesan + "','"
                + makanan + "','"
                + minuman + "','"
                + totalBayar + "','"
                + uangBayar + "','"
                + (uangBayar - totalBayar) + "','"
                + tDate.format(timer.getTime()) + "','"
                + tTime.format(timer.getTime()) + "')";

        St.executeUpdate(sql);

        // Menutup statement dan koneksi
        St.close();
        connection.close();

        // Menambahkan pesan pada JTextArea
        jTextArea1.append("\t Aplikasi TotalBite  \n\n" +
                " No Order : \t\t" + nomerOrder + "\n" +
                " Pemesan : \t\t" + namaPemesan + "\n" +
                "\n===========================\n" +
                " Makanan : \t\t" + makanan + "\n\n" +
                " Minuman : \t\t" + minuman + "\n\n" +
                " Total Pesanan : \t" + jText13.getText() + "\n" +
                "\n===========================\n" +
                " SubTotal : \t\t" + jText14.getText() + "\n\n" +
                " PPN : \t\t" + jText15.getText() + "\n\n" +
                " Total Bayar : \t\t" + jText16.getText() + "\n\n" +
                " Uang Bayar : \t\t" + jText17.getText() + "\n\n" +
                " Kembalian : \t\t" + jText18.getText() + "\n" +
                "\n===========================\n" +
                "\n Tanggal : " + tDate.format(timer.getTime()) +
                "\n Waktu : " + tTime.format(timer.getTime()) +
                "\n\n\n Terima Kasih..");

    } catch (SQLException e) {
        // Menangani kesalahan SQL, misalnya mencetak error atau melakukan log
        e.printStackTrace();
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jText17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText17ActionPerformed
        // Bayar
    }//GEN-LAST:event_jText17ActionPerformed

    private void jText18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText18ActionPerformed
        // Kembalian
    }//GEN-LAST:event_jText18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Print
        try {
            // Mencetak konten jTextArea1
            boolean completed = jTextArea1.print();

            if (completed) {
                JOptionPane.showMessageDialog(this, "Cetak selesai.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Cetak dibatalkan.", "Informasi", JOptionPane.WARNING_MESSAGE);
            }
        } catch (PrinterException e) {
            // Tangani kesalahan jika terjadi masalah saat mencetak
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencetak.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jText19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText19ActionPerformed
        // Nama Pemesan
    }//GEN-LAST:event_jText19ActionPerformed

    private void jButtonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataActionPerformed
    // Menampilkan Data Penjualan
        DataPenjualan datapenjualan = new DataPenjualan ();
        datapenjualan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDataActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalBite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalBite().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonData;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText10;
    private javax.swing.JTextField jText11;
    private javax.swing.JTextField jText12;
    private javax.swing.JTextField jText13;
    private javax.swing.JTextField jText14;
    private javax.swing.JTextField jText15;
    private javax.swing.JTextField jText16;
    private javax.swing.JTextField jText17;
    private javax.swing.JTextField jText18;
    private javax.swing.JTextField jText19;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jText4;
    private javax.swing.JTextField jText5;
    private javax.swing.JTextField jText6;
    private javax.swing.JTextField jText7;
    private javax.swing.JTextField jText8;
    private javax.swing.JTextField jText9;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
